"""initial schema

Revision ID: b5e3559115d8
Revises: 
Create Date: 2026-08-14 13:31:50.374179

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b5e3559115d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_user_id'), 'users', ['google_user_id'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_last_activity_at'), 'chats', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_chats_owner_id'), 'chats', ['owner_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_type', sa.Enum('MAIN', 'CHILD', name='branch_type'), nullable=False),
    sa.Column('parent_branch_id', sa.Uuid(), nullable=True),
    sa.Column('base_message_block_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_message_block_id'], ['message_blocks.id'], name='fk_branches_base_message_block', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_chat_id'), 'branches', ['chat_id'], unique=False)
    op.create_index(op.f('ix_branches_parent_branch_id'), 'branches', ['parent_branch_id'], unique=False)
    op.create_table('block_refine_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'COMPLETED', 'FAILED', name='refine_job_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_refine_jobs_branch_id'), 'block_refine_jobs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_block_refine_jobs_chat_id'), 'block_refine_jobs', ['chat_id'], unique=False)
    op.create_table('branch_source_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('source_branch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_source_contexts_branch_id'), 'branch_source_contexts', ['branch_id'], unique=True)
    op.create_table('message_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_version_id'], ['message_block_versions.id'], name='fk_message_blocks_current_version', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'order_index', name='uq_block_branch_order')
    )
    op.create_index(op.f('ix_message_blocks_branch_id'), 'message_blocks', ['branch_id'], unique=False)
    op.create_index(op.f('ix_message_blocks_chat_id'), 'message_blocks', ['chat_id'], unique=False)
    op.create_table('applied_context_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('user_message_block_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_block_id'], ['message_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_context_logs_branch_id'), 'applied_context_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_applied_context_logs_chat_id'), 'applied_context_logs', ['chat_id'], unique=False)
    op.create_index(op.f('ix_applied_context_logs_user_message_block_id'), 'applied_context_logs', ['user_message_block_id'], unique=False)
    op.create_table('branch_source_context_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_context_id', sa.Uuid(), nullable=False),
    sa.Column('source_message_block_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_context_id'], ['branch_source_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_block_id'], ['message_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_source_context_items_source_context_id'), 'branch_source_context_items', ['source_context_id'], unique=False)
    op.create_table('message_block_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('ORIGINAL', 'USER_EDIT', 'AI_REFINE', 'AI_REGENERATE', name='version_source_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['message_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'version_no', name='uq_version_block_no')
    )
    op.create_index(op.f('ix_message_block_versions_block_id'), 'message_block_versions', ['block_id'], unique=False)
    op.create_table('applied_context_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('source_block_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['applied_context_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_block_id'], ['message_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['message_block_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_context_items_log_id'), 'applied_context_items', ['log_id'], unique=False)
    op.create_table('block_refine_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('base_version_id', sa.Uuid(), nullable=False),
    sa.Column('refined_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='refine_result_status'), nullable=False),
    sa.Column('approved_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_version_id'], ['message_block_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['base_version_id'], ['message_block_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id'], ['message_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['block_refine_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_refine_results_block_id'), 'block_refine_results', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_refine_results_job_id'), 'block_refine_results', ['job_id'], unique=False)
    op.create_table('block_refine_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('base_version_id', sa.Uuid(), nullable=False),
    sa.Column('base_content', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='message_role'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['message_block_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id'], ['message_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['block_refine_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_refine_targets_job_id'), 'block_refine_targets', ['job_id'], unique=False)
    # ### end Alembic commands ###

    # branches <-> message_blocks, message_blocks <-> message_block_versions 는 순환 참조라
    # 모델에서 use_alter=True 로 선언했다. use_alter 는 metadata.create_all() 에서만 자동
    # 처리되고 op.create_table() 에서는 제약이 생성되지 않으므로, 양쪽 테이블이 모두 만들어진
    # 뒤 여기서 명시적으로 추가한다.
    op.create_foreign_key(
        'fk_branches_base_message_block', 'branches', 'message_blocks',
        ['base_message_block_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_message_blocks_current_version', 'message_blocks', 'message_block_versions',
        ['current_version_id'], ['id'], ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint('fk_message_blocks_current_version', 'message_blocks', type_='foreignkey')
    op.drop_constraint('fk_branches_base_message_block', 'branches', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_refine_targets_job_id'), table_name='block_refine_targets')
    op.drop_table('block_refine_targets')
    op.drop_index(op.f('ix_block_refine_results_job_id'), table_name='block_refine_results')
    op.drop_index(op.f('ix_block_refine_results_block_id'), table_name='block_refine_results')
    op.drop_table('block_refine_results')
    op.drop_index(op.f('ix_applied_context_items_log_id'), table_name='applied_context_items')
    op.drop_table('applied_context_items')
    op.drop_index(op.f('ix_message_block_versions_block_id'), table_name='message_block_versions')
    op.drop_table('message_block_versions')
    op.drop_index(op.f('ix_branch_source_context_items_source_context_id'), table_name='branch_source_context_items')
    op.drop_table('branch_source_context_items')
    op.drop_index(op.f('ix_applied_context_logs_user_message_block_id'), table_name='applied_context_logs')
    op.drop_index(op.f('ix_applied_context_logs_chat_id'), table_name='applied_context_logs')
    op.drop_index(op.f('ix_applied_context_logs_branch_id'), table_name='applied_context_logs')
    op.drop_table('applied_context_logs')
    op.drop_index(op.f('ix_message_blocks_chat_id'), table_name='message_blocks')
    op.drop_index(op.f('ix_message_blocks_branch_id'), table_name='message_blocks')
    op.drop_table('message_blocks')
    op.drop_index(op.f('ix_branch_source_contexts_branch_id'), table_name='branch_source_contexts')
    op.drop_table('branch_source_contexts')
    op.drop_index(op.f('ix_block_refine_jobs_chat_id'), table_name='block_refine_jobs')
    op.drop_index(op.f('ix_block_refine_jobs_branch_id'), table_name='block_refine_jobs')
    op.drop_table('block_refine_jobs')
    op.drop_index(op.f('ix_branches_parent_branch_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_chat_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_chats_owner_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_activity_at'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_google_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Alembic 은 PostgreSQL ENUM 타입을 자동으로 정리하지 않는다. 남겨두면 재적용 시
    # "type already exists" 로 실패하므로 명시적으로 삭제한다.
    for enum_name in (
        'branch_type',
        'message_role',
        'version_source_type',
        'refine_job_status',
        'refine_result_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
